### PR TITLE
Fullscreen mode

### PR DESCRIPTION
**Pull request by solilokiam**
I've missed the functionality of going fullscreen. I don't like to see browser window when doing my presentations, so I created the functionality of going fullscreen using Fullscreen API.

To make it work you just need to push F key. Maybe this is not the perfect key assignment, suggestions welcome.

### CODE REVIEW

**Comment by Belelros** [comment]
Hey @solilokiam this looks great and the `F` is a great key for that thanks for putting your time into this, we missed this as we've been focused on presentations and projectors hide the browser interface so it's **great** that you brought it up. 

A few *really* minor pieces:

Can you remove from the PR the built files?
Also, how familiar are you on writing tests? If that's something you'd make (we would been even more grateful) then please, could you make this based from the dev branch and PR to said branch? We got [Jest](https://facebook.github.io/jest/) there and working to make sure our codebase is fully tested. If this feels too much just let me know, I can deal with it later.
Finally and mostly nitpick, could you normalise the order of the prefixed? `requestFullScreen` is the only one that's succeeded by `webkit` whereas the others are succeeded by `moz` I'd rather use `webkit` as the second one but it doesn't really matter.

Again, great work! Let me know your thoughts on my comments.

**Comment by solilokiam** [comment]
@Belelros you can close this PR. I will open a new one to dev branch with the changes you suggested.

**Comment by Belelros** [comment]
We need to point this to `dev`. Otherwise the PR gets really polluted

**Comment by solilokiam** [comment]
@Belelros I've added the tests and done everything you asked. Is there anything more you need?

**Comment by Belelros** [comment]
Thanks a lot for this @solilokiam !

**Pull request merged**
